version: '3.8'

services:
  search-reranking-system:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TURBOPUFFER_API_KEY=${TURBOPUFFER_API_KEY}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - OAI_KEY=${OAI_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/search/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  logs:
    driver: local